#! /bin/sh
if   [ "configure" = "$1" && "." = ".$2" ]; then  shift ; set -- "1" "$@"
elif [ "configure" = "$1" && "." != ".$2" ]; then shift ; set -- "2" "$@"
fi

# HACK - https://bugzilla.redhat.com/show_bug.cgi?id=1185749
( cd /var/lib/pcp/pmns && ./Rebuild -du )
# HACK - https://bugzilla.redhat.com/show_bug.cgi?id=1185764
# We can't use "systemctl reload-or-try-restart" since systemctl might
# be out of sync with reality.
/usr/share/pcp/lib/pmlogger reload

#DEBHELPER#
